-- NCP 자원(K8S / OBJECT_STORAGE) 일별 비용 — ncp_cost_vm_daily 와 동일하게 월 누적(ncp_cost_resource_month)의 전일 차분
--   공유 DDL(mysql/init_cost_db_ddl.sql) 의 동일 블록과 내용을 맞출 것.
CREATE TABLE IF NOT EXISTS ncp_cost_resource_daily
(
    id                        BIGINT AUTO_INCREMENT NOT NULL COMMENT '아이디',
    created                   datetime              NULL     COMMENT 'row insert 시간',
    updated                   datetime              NULL     COMMENT 'row update 시간',
    member_no                 VARCHAR(100)          NOT NULL COMMENT '회원 번호',
    demand_month              VARCHAR(6)            NOT NULL COMMENT '청구 월. ex) 202510',
    region_code               VARCHAR(10)           NOT NULL DEFAULT 'KR' COMMENT '리전 코드',
    resource_type             VARCHAR(20)           NOT NULL COMMENT 'K8S | OBJECT_STORAGE',
    demand_type_code          VARCHAR(20)           NOT NULL COMMENT '청구 유형 코드',
    demand_type_name          VARCHAR(100)          NULL,
    demand_type_detail_code   VARCHAR(20)           NOT NULL DEFAULT '' COMMENT '청구 유형 상세 코드',
    demand_type_detail_name   VARCHAR(100)          NULL,
    contract_no               VARCHAR(50)           NOT NULL DEFAULT '' COMMENT '계약 번호',
    product_code              VARCHAR(50)           NULL,
    product_name              VARCHAR(200)          NULL,
    instance_no               VARCHAR(100)          NULL     COMMENT 'NCP 인스턴스 번호(원본)',
    instance_name             VARCHAR(200)          NULL     COMMENT 'NCP 인스턴스 이름(원본)',
    resource_id               VARCHAR(200)          NOT NULL COMMENT 'servicegroup_meta.csp_instanceid 조인 키',
    resource_name             VARCHAR(200)          NULL,
    resource_id_source        VARCHAR(20)           NOT NULL COMMENT 'NKS_UUID | INSTANCE_NO | CONTRACT_NO',
    usage_unit_code           VARCHAR(50)           NOT NULL DEFAULT '',
    usage_unit_name           VARCHAR(100)          NOT NULL DEFAULT '',
    product_price             DOUBLE                NOT NULL DEFAULT 0,
    unit_usage_quantity       DOUBLE                NOT NULL DEFAULT 0,
    total_unit_usage_quantity DOUBLE                NOT NULL DEFAULT 0,
    use_amount                DOUBLE                NOT NULL COMMENT '사용 금액(누적, KRW)',
    demand_amount             DOUBLE                NOT NULL COMMENT '청구 금액(누적, KRW)',
    write_date                datetime              NOT NULL COMMENT 'NCP 작성 일시',
    pay_currency              VARCHAR(10)           NOT NULL COMMENT '결제 통화. ex) KRW',
    target_date               DATE                  NOT NULL COMMENT '대상 날짜 (= DATE(write_date))',
    daily_charge_amount       DOUBLE                NOT NULL COMMENT '일별 청구 금액 (전일 누적 대비 차이, KRW)',
    CONSTRAINT pk_ncp_cost_resource_daily PRIMARY KEY (id) COMMENT 'NCP 자원(K8S/ObjectStorage)별 일별 청구 비용',
    CONSTRAINT uk_ncp_cost_resource_daily UNIQUE (member_no, demand_month, resource_type, resource_id, region_code, demand_type_detail_code, contract_no, target_date),
    INDEX idx_ncr_daily_type_rid_date (resource_type, resource_id, target_date),
    INDEX idx_ncr_daily_rid_date (resource_id, target_date),
    INDEX idx_ncr_daily_target_date (target_date),
    INDEX idx_ncr_daily_month (demand_month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
