openapi: "3.1.0"
info:
  title: "Cost Azure Collector API"
  description: "Cost Azure Collector API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8093"
paths:
  /api/batch/azure/service:
    get:
      summary: "Azure Service 들의 전날의 이용 금액을 수집한다."
      operationId: "batchAzureService"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /api/batch/azure/vm:
    get:
      summary: "Azure VM 들의 전날의 이용 금액을 수집한다."
      operationId: "batchAzureVm"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"