version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: local-mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: root
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: