name: MC-CostOpti-BE-TEST (CI)

on:
  push:
    branches:
      - cicd/241030_gitaction
    paths-ignore:
      - "AlarmService/**"
      - "assetCollector/**"
      - "cost-fe/**"
      - "costCollector/**"
      - "costProcessor/**"
      - "costSelector/**"
      - "mysql/**"
      - "**.md"
      - "LICENSE.txt"
      - ".gitignore"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "AlarmService/**"
      - "assetCollector/**"
      - "cost-fe/**"
      - "costCollector/**"
      - "costProcessor/**"
      - "costSelector/**"
      - "mysql/**"
      - "**.md"
      - "LICENSE.txt"
      - ".gitignore"

jobs:
  publish-container-image:
    name: Publish a container image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file BackEnd/pom.xml

      - name: List target directory
        run: ls -la BackEnd/target

      - name: Build image
        run: docker build --progress=plain --file BackEnd/Dockerfile -t mc-costopti-api-test ./BackEnd
